---

- block:

  - name: Copy manifests
    template: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: kubelet.service.j2, dest: /etc/systemd/system/kubelet.service }
      - { src: kube-scheduler.yml.j2, dest: /etc/kubernetes/manifests/kube-scheduler.yml }
      - { src: kube-proxy.yml.j2, dest: /etc/kubernetes/manifests/kube-proxy.yml }
      - { src: kube-controller.yml.j2, dest: /etc/kubernetes/manifests/kube-controller.yml }
      - { src: kube-apiserver.yml.j2, dest: /etc/kubernetes/manifests/kube-apiserver.yml }
      - { src: kube-addon-manager.yml.j2, dest: /etc/kubernetes/manifests/kube-addon-manager.yml }

  - name: Start kubelet
    shell: |
      systemctl stop kubelet.service
      systemctl daemon-reload
      systemctl enable kubelet.service
      systemctl start kubelet.service

  - name: Wait for Kube-apiserver to start responding on localhost:8080
    wait_for: port=8080 delay=1
  
  become: true
  become_method: sudo
