---

docker_hyperkube: "{{ docker_kube_hyperkube_image.registry }}/{{ docker_kube_hyperkube_image.name }}:{{ docker_kube_hyperkube_image.tag }}"
docker_addonManager: "{{ docker_kube_addonManager_image.registry }}/{{ docker_kube_addonManager_image.name }}:{{ docker_kube_addonManager_image.tag }}"

apiServer_tls_cert: "{{ kube_certs_dir }}/api-server.pem"
apiServer_tls_key: "{{ kube_certs_dir }}/api-server-key.pem"
