---

docker_hyperkube: "{{ docker_kube_hyperkube_image.registry }}/{{ docker_kube_hyperkube_image.name }}:{{ docker_kube_hyperkube_image.tag }}"
docker_addonManager: "{{ docker_kube_addonManager_image.registry }}/{{ docker_kube_addonManager_image.name }}:{{ docker_kube_addonManager_image.tag }}"

apiServer_tls_cert: "{{ kube_certs_dir }}/api-server.pem"
apiServer_tls_key: "{{ kube_certs_dir }}/api-server-key.pem"

serviceAccountTokens_cert: "{{ kube_certs_dir }}/service-account-tokens.pem"
serviceAccountTokens_key: "{{ kube_certs_dir }}/service-account-tokens-key.pem"

kubernetesSshId_priv: "{{ kube_certs_dir }}/kubernetes-ssh-id"
kubernetesSshId_pub: "{{ kube_certs_dir }}/kubernetes-ssh-id.pub"
kubernetesSshId_user: core
