apiVersion: "v1"
kind: "Service"
metadata:
  name: "heapster"
  namespace: "kube-system"
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "heapster"
spec:
  #type: NodePort
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8082
  selector: 
    k8s-app: "heapster"
