apiVersion: v1
kind: ReplicationController
metadata:
  name: heapster-v1.1.0-beta2
  namespace: kube-system
  labels:
    k8s-app: heapster
    kubernetes.io/cluster-service: "true"
    version: v1.1.0-beta2 
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v1.1.0-beta2
  template:
    metadata:
      labels:
        k8s-app: heapster
        kubernetes.io/cluster-service: "true"
        version: v1.1.0-beta2
    spec:
      containers:
        - name: heapster
          image: gcr.io/google_containers/heapster:v1.1.0-beta2
          command:
            - "/heapster"
            - "--source=kubernetes.summary_api:http://172.17.4.51:8080?inClusterConfig=false"
            - "--metric_resolution=60s"
            - "--sink=influxdb:http://10.3.0.161:8086&withfields=true"
          ports:
            - name: api
              containerPort: 8082
              protocol: TCP
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 250Mi
            requests:
              cpu: 100m
              memory: 250Mi
        - name: eventer
          image: gcr.io/google_containers/heapster:v1.1.0-beta2
          command:
            - "/eventer"
            - "--source=kubernetes:http://172.17.4.51:8080?inClusterConfig=false"
            - "--sink=influxdb:http://10.3.0.161:8086&withfields=true"
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
