apiVersion: v1
kind: ReplicationController
metadata:
  name: influxdb-grafana
  namespace: kube-system
  labels:
    k8s-app: influxdb-grafana
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: influxdb-grafana
  template:
    metadata:
      labels:
        k8s-app: influxdb-grafana
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: influxdb
        image: gcr.io/google_containers/heapster_influxdb:v0.6
        ports:
          - name: ui
            containerPort: 8083
            port: TCP
          - name: api
            containerPort: 8086
            port: TCP
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      - name: grafana
        image: gcr.io/google_containers/heapster_grafana:v2.6.0-2
        ports:
          - name: ui
            containerPort: 3000
            port: TCP
        env:
          - name: INFLUXDB_SERVICE_URL
            value: http://10.3.0.161:8086
            # The following env variables are required to make Grafana accessible via
            # the kubernetes api-server proxy. On production clusters, we recommend
            # removing these env variables, setup auth for grafana, and expose the grafana
            # service using a LoadBalancer or a public IP.
          - name: GF_AUTH_BASIC_ENABLED
            value: "false"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            value: Admin
          - name: GF_SERVER_ROOT_URL
            value: /api/v1/proxy/namespaces/kube-system/services/heapster-grafana
        volumeMounts:
        - mountPath: /var
          name: grafana-storage
      volumes:
      - name: influxdb-storage
        emptyDir: {}
      - name: grafana-storage
        emptyDir: {}
