---

- name: Download Kubelet and Kubectl binaries
  raw:  wget  --continue --directory-prefix {{ work_dir }} {{ kube_binaries_download_url_base }}/{{ item }}
  with_items:
    - "{{ kube_binaries_download_filenames }}"

- name: Download weave helper
  raw:  wget  --continue --directory-prefix {{ work_dir }} {{ weave_helper_download_url }}

- name: Change mode to executable on downloaded files
  file: path={{ work_dir }}/{{ item }} state=file mode=a+x
  with_items:
    - "{{ kube_binaries_download_filenames }}"
      
- name: Download RKT flannel.aci
  raw:  wget  --continue  --output-document={{ work_dir }}/{{ rtk_flannelAci_filename }} {{ rtk_flannelAci_download_url }}   

- name: Download CNI plugins version {{ cni_version }}
  raw:  wget  --continue  --output-document={{ work_dir }}/{{ cni_plugins_download_url | basename }} {{ cni_plugins_download_url }}   


