---

- name: Create Registry Volume
  shell: >
    docker volume ls | grep registry-mount > /dev/null 
    || docker volume create --name registry-mount
  changed_when: command_result.stdout_lines | length > 0
  register: command_result

- name: Start Registry Container
  shell: >
    docker ps --filter=ancestor={{ item.name }}:{{ item.tag }} | grep {{ item.name }}:{{ item.tag }} > /dev/null 
    || docker run -d --restart on-failure --name registry -v registry-mount:/var/lib/registry -p 5000:5000 {{ item.name }}:{{ item.tag }}
  with_items:
    - "{{ docker_registry_image }}"
  register: command_result
  changed_when: command_result.stdout_lines | length > 0

- name: Pull required docker images
  shell: >
    docker images | grep '{{ item.registry}}/{{ item.name }} *{{ item.tag }}' > /dev/null 
    || docker pull {{ item.registry }}/{{ item.name}}:{{ item.tag }}
  with_items:
    - "{{ docker_flannel_images }}" 
    - "{{ docker_kube_hyperkube_image }}"
    - "{{ docker_kube_dns_images }}"
    - "{{ docker_kube_ui_images }}"
    - "{{ docker_kube_heapster_images }}"
  register: command_result
  changed_when: command_result.stdout_lines | length > 0

- name: Push images to Registry
  shell: >
    docker tag {{ item.registry }}/{{ item.name }}:{{ item.tag }} localhost:5000/{{ item.name }}:{{ item.tag }}
    && docker push localhost:5000/{{ item.name }}:{{ item.tag }}
  with_items:
    - "{{ docker_flannel_images }}" 
    - "{{ docker_kube_hyperkube_image }}"
    - "{{ docker_kube_dns_images }}"
    - "{{ docker_kube_ui_images }}"
    - "{{ docker_kube_heapster_images }}"
  register: command_result
  changed_when: "command_result.stdout | lower | search('pushed')"

#- debug: var=command_result







  


