---

- name: INCLUDE Prepare TLS certs
  include: prep-certs.yml

- block:
  - name: Ensure systemd etcd unit config folder
    file: path=/etc/systemd/system/etcd2.service.d state=directory recurse=true

  - name: Extend etcd with Environment file
    template: src=20-environment.conf.j2 dest=/etc/systemd/system/etcd2.service.d/20-environment.conf 
  
  - name: Create new etcd cluster when 'new_etcd_cluster' environment flag equals true
    file: path=/var/lib/etcd2/member state=absent
    when: new_etcd_cluster | default(false)

  - name: Enable etcd
    shell: |
      systemctl daemon-reload
      systemctl enable etcd2.service
      systemctl restart etcd2.service
  become: true
  become_method: sudo


