---

- name: Load Kubernetes Master docker images
  shell: >
    docker images | grep '{{ item.registry }}/{{ item.name }} *{{ item.tag }}' > /dev/null 
    || docker load < {{ item.name }}-{{ item.tag }}
  args:
    chdir: "{{ work_images_dir }}"
  with_items:
    - "{{ docker_kube_hyperkube_image }}"
    - "{{ docker_kube_addonManager_image }}"
  register: command_result
  changed_when: command_result.stdout_lines | length > 0
  when: "'kube-masters' in group_names"
  
- name: Load Kubernetes Worker docker images
  shell: >
    docker images | grep '{{ item.registry }}/{{ item.name }} *{{ item.tag }}' > /dev/null 
    || (ls  | grep -q {{ item.name }}-{{ item.tag }} && docker load < {{ item.name }}-{{ item.tag }})
    || exit 0
  args:
    chdir: "{{ work_images_dir }}"
  with_items:
    - "{{ docker_kube_hyperkube_image }}"
    - "{{ docker_kube_addons_images }}"
  register: command_result
  changed_when: command_result.stdout_lines | length > 0
  when: "'kube-addon-workers' in group_names"


