---

- name: INCLUDE Import cached docker images for kube-node
  include: import-docker-cached-images.yml

- name: INCLUDE Import cached rtk images for flannel
  include: import-rkt-cached-images.yml

- name: INCLUDE Import kublet, kubectl and CNI binaries
  include: import-binaries.yml

- name: Ensure kube-node configuration directories
  file: path={{ item }} state=directory recurse=true
  with_items:
    - "{{ kube_certs_dir }}"
    - "{{ kube_manifests_dir }}" 
    - "{{ kube_addons_dir }}"
    - "{{ kube_admissionControls_dir }}"
  become: true
  become_method: sudo


- name: INCLUDE Prepare system-account Kubeconfig
  include: prep-system-kubeconfig.yml

