---

- block:
    
  - name: Un-tar system-account certs into kube-certs directory
    shell: >
      ls {{ work_certs_dir }} | grep -q system-account-user.tar 
      && tar -xf {{ work_certs_dir }}/system-account-user.tar -C {{ kube_certs_dir }} 
      && rm -f {{ work_certs_dir }}/system-account-user.tar
      
  - name: Make root the owner of its TLS directory
    file: path={{ kube_certs_dir }} owner=root group=root recurse=true 
    with_items:
      - "{{ kube_certs_dir }}"
    
  - name: Set appropriate permissions for certificates
    raw: |
      chmod {{ item.permission }} {{ item.path }}
    with_items:
      - { path: "{{ kube_systemAccount_cert }}", permission: "0400" }
      - { path: "{{ kube_systemAccount_key }}", permission: "0400" }

  - name: Create kube-config on each node
    template: src=cluster-kubeconfig.j2 dest={{ kube_cluster_config }}

  become: true
  become_method: sudo


