---

etcd_endpoint_scheme: https
etcd_endpoints: "{% for hostname in groups['etcd'] %}{{ etcd_endpoint_scheme }}://{{ hostname }}:2379{% if not loop.last %},{% endif %}{% endfor %}"

master_endpoint_scheme: http
master_endpoints: "{% for hostname in groups['kube-masters'] %}{{ master_endpoint_scheme }}://{{ hostname }}:8080{% if not loop.last %},{% endif %}{% endfor %}"

flanel_network_block: 10.1.0.0/16
flannel_network_backend_type: vxlan

kube_services_network_block: 10.3.0.0/24
kube_dns_service_ip: "{{ kube_services_network_block | ipaddr('net') | ipaddr(10) | ipaddr('address') }}"
kube_api_service_ip: "{{ kube_services_network_block | ipaddr('net') | ipaddr(1) | ipaddr('address') }}"
kube_ca_cert: /etc/ssl/certs/kube-ca.pem

# Directory where we copy and work with files
home_dir: /home/core
work_dir: "{{ home_dir }}/prep-files"
work_certs_dir: "{{ work_dir }}/certs"

# Directory where custom executables are run from in CoreOS
opt_dir: /opt
opt_bin_dir: "{{ opt_dir }}/bin"


