---

google_registry: gcr.io/google_containers

# MASTER IMAGES
kube_version: 1.4.3
docker_kube_hyperkube_image: { name: "hyperkube", tag: "v{{ kube_version }}", registry: "{{ google_registry }}" }
docker_kube_addonManager_image: { name: "kube-addon-manager", tag: "v5.1", registry: "{{ google_registry }}" }


# ADDON WORKER IMAGES
docker_kube_dns_dns_image: { name: "kubedns-amd64", tag: "1.8", registry: "{{ google_registry }}" }
docker_kube_dns_mask_image: { name: "kube-dnsmasq-amd64", tag: "1.4", registry: "{{ google_registry }}" }
docker_kube_dns_health_image: { name: "exechealthz-amd64", tag: "1.2", registry: "{{ google_registry }}" }
docker_kube_dns_images: 
  - "{{ docker_kube_dns_dns_image }}"
  - "{{ docker_kube_dns_mask_image }}"
  - "{{ docker_kube_dns_health_image }}"

docker_kube_heapster_images:
  - { name: "heapster", tag: "v1.1.0-beta2", registry: "{{ google_registry }}" }
  - { name: "heapster_influxdb", tag: "v0.6", registry: "{{ google_registry }}" }
  - { name: "heapster_grafana", tag: "v2.6.0-2", registry: "{{ google_registry }}" }

docker_kube_ui_image: { name: "kubernetes-dashboard-amd64", tag: "v1.4.1", registry: "{{ google_registry }}" }

# FLANNEL IMAGES
rtk_flannelAci_download_url: https://quay.io/c1/aci/quay.io/coreos/flannel/0.5.5/aci/linux/amd64/
rtk_flannelAci_filename: flannel.aci

# BINARIES
kube_binaries_download_url_base: https://storage.googleapis.com/kubernetes-release/release/v{{ kube_version }}/bin/linux/amd64
kube_binaries_download_filenames:
  - kubelet
  - kubectl



