---

- name: Move kubectl from {{ work_dir }} into {{ opt_bin_dir }}
  shell: >
    ls {{ item }} > /dev/null && cp {{ item }} {{ opt_bin_dir }} 
  args:
    chdir: "{{ work_dir }}"
  with_items: 
    - kubectl
  register: command_result
  failed_when: false
  changed_when: command_result | succeeded


- name: INCLUDE Prepare cluster-admin kubeconfig
  include: prep-admin-kubeconfig.yml


