---

- block:
  - name: Copy Master SSH public key to nodes for tunneling from master to nodes
    synchronize: src={{ work_certs_dir }}/kubernetes-ssh-id.pub dest={{ home_dir }}/.ssh/authorized_keys.d/
    delegate_to: "{{ groups['agent'] | first }}"

  - name: Re-synch authorized_keys from {{ home_dir }}/.ssh/authorized_keys.d
    shell: cat {{ ssh_dir }}/authorized_keys.d/* > {{ ssh_dir }}/authorized_keys 
  vars:
    ssh_dir: "{{ home_dir }}/.ssh"

