---

- name: Set kubeconfig_bundle_dir and bundled_certs_tar facts
  set_fact:
    kubeconfig_bundle_dir: "{{ home_dir}}/kubeconfig-bundle"
    bundled_certs_tar: "{{ kube_clusterAdmin_cert | basename | splitext | first }}.tar"

- name: Ensure directory {{ kubeconfig_bundle_dir }}
  file: path={{ kubeconfig_bundle_dir }} state=directory recurse=true

- name: Create default inner cluster kubeconfig
  template: src=templates/admin-kubeconfig.j2 dest={{ kubeconfig_bundle_dir }}/config
  vars:
    remote_kube_ca_cert: "{{ kube_ca_cert | basename }}"
    remote_admin_cert: "{{ kube_clusterAdmin_cert | basename }}"
    remote_admin_key: "{{ kube_clusterAdmin_key | basename }}"


- name: Un-tar cluster-admin certs into {{ kubeconfig_bundle_dir }} directory
  shell: >
    ls {{ work_certs_dir }} | grep -q {{ bundled_certs_tar }} 
    && tar -xf {{ work_certs_dir }}/{{ bundled_certs_tar }} -C {{ kubeconfig_bundle_dir }} 
  args:
    creates: "{{ kube_clusterAdmin_key | basename }}"
      
- name: Copy {{ kube_ca_cert }} into {{ kubeconfig_bundle_dir }}
  shell: cp -f {{ item }} {{ kubeconfig_bundle_dir }}
  with_items:
    - "{{ work_certs_dir }}/{{ kube_ca_cert | basename }}"
  changed_when: false

- name: Set appropriate permissions for certificates
  shell: |
    chmod {{ item.permission }} {{ item.path }}
  args:
    chdir: "{{ kubeconfig_bundle_dir }}"
  with_items:
    - { path: "{{ kube_clusterAdmin_cert | basename }}", permission: "0400" }
    - { path: "{{ kube_clusterAdmin_key | basename }}", permission: "0400" }
    - { path: "{{ kube_ca_cert | basename }}", permission: "0400" }



