---

- block:
  - name: Move kube-ca to /etc/ssl/certs and reload certs
    shell: >
      cp {{ work_certs_dir }}/{{ kube_ca_cert | basename }} {{ kube_ca_cert }} 
      && update-ca-certificates
    args:
      creates: "{{ kube_ca_cert }}"

  - name: Set cluster certificate permission and ownership
    file: path={{ kube_ca_cert }} mode=0444 owner=root group=root 

  become: true
  become_method: sudo


- name: Remove unnecesary etcd cert files from {{ work_dir }}
  file: path={{ work_dir }}/certs/{{ item }} state=absent
  with_items:
    - api-server.tar
    - "{{ kube_ca_cert | basename }}"
    - system-account-user.tar
  when: "'etcd' in group_names"
  changed_when: false

- name: Remove unnecesary kube-node cert files from {{ work_dir }}
  file: path={{ work_dir }}/certs/{{ item }} state=absent
  with_items:
    - etcd.tar
    - "{{ kube_ca_cert | basename }}"
  when: "'kube-nodes' in group_names"
  changed_when: false

- name: Remove unnecesary kube-worker cert files from {{ work_dir }}
  file: path={{ work_dir }}/certs/{{ item }} state=absent
  with_items:
    - api-server.tar
    - "{{ kube_ca_cert | basename }}"
  when: "'kube-addon-workers' in group_names"
  changed_when: false

