---

- name: Copy {{ work_dir }} from agent
  synchronize: 
    src: "{{ work_dir }}"
    dest: "{{ home_dir }}"
    mode: push
    compress: no
    recursive: true
  delegate_to: "{{ groups['agent'] | first }}"

