---

- name: Copy {{ work_dir }} from agent
  synchronize: 
    src: "{{ work_dir }}"
    dest: "{{ home_dir }}"
    mode: push
    compress: no
    recursive: true
  delegate_to: "{{ groups['agent'] | first }}"

- name: Copy {{ work_images_dir }} from agent
  synchronize: 
    src: "{{ work_images_dir }}"
    dest: "{{ home_dir }}"
    mode: push 
    compress: no
    recursive: true 
    rsync_opts:
      - "--include='*/'"
      - "--include='{{ docker_kube_hyperkube_image.name  }}*'"
      - "--exclude='*'"
  delegate_to: "{{ groups['agent'] | first }}"
  when: "'kube-nodes' in group_names"

- name: Copy {{ work_images_dir }} from agent
  synchronize: 
    src: "{{ work_images_dir }}"
    dest: "{{ home_dir }}"
    mode: push 
    compress: no
    recursive: true 
    rsync_opts:
      - "--include='*/'"
      - "--include='{{ docker_kube_addonManager_image.name }}*'"
      - "--exclude='*'"
  delegate_to: "{{ groups['agent'] | first }}"
  when: "'kube-masters' in group_names"

- name: Copy {{ work_images_dir }} from agent
  synchronize: 
    src: "{{ work_images_dir }}"
    dest: "{{ home_dir }}"
    mode: push 
    compress: no
    recursive: true 
    rsync_opts:
      - "--include='*/'"
      - "{% for item in docker_kube_dns_images %}--include='{{ item.name }}*' {% endfor %}"
      - "--exclude='*'"
  delegate_to: "{{ groups['agent'] | first }}"
  when: "'kube-addon-workers' in group_names"



