---

- name: Transfer hyperkube docker images from agent to [kube-nodes] 
  synchronize: 
    src: "{{ work_images_dir }}"
    dest: "{{ home_dir }}"
    mode: push 
    compress: no
    recursive: true 
    rsync_opts:
      - "--include='*/'"
      - "--include='{{ docker_kube_hyperkube_image.name  }}*'"
      - "--exclude='*'"
  delegate_to: "{{ groups['agent'] | first }}"
  when: "'kube-nodes' in group_names"

- name: Transfer addonManager docker images from agent to [kube-masters]
  synchronize: 
    src: "{{ work_images_dir }}"
    dest: "{{ home_dir }}"
    mode: push 
    compress: no
    recursive: true 
    rsync_opts:
      - "--include='*/'"
      - "--include='{{ docker_kube_addonManager_image.name }}*'"
      - "--exclude='*'"
  delegate_to: "{{ groups['agent'] | first }}"
  when: "'kube-masters' in group_names"

- name: Transfer addon docker images from agent to [kube-addon-workers]
  synchronize: 
    src: "{{ work_images_dir }}"
    dest: "{{ home_dir }}"
    mode: push 
    compress: no
    recursive: true 
    rsync_opts:
      - "--include='*/'"
      - "{% for item in docker_kube_addons_images %}--include='{{ item.name }}*' {% endfor %}"
      - "--exclude='*'"
  delegate_to: "{{ groups['agent'] | first }}"
  when: "'kube-addon-workers' in group_names"



