---

# Make sure the id_rsa key is present to talk to other nodes from the agent node
- hosts: agent
  tasks:
  - name: Stat file {{ home_dir }}/.ssh/id_rsa
    stat: path={{ home_dir }}/.ssh/id_rsa
    register: command_result
  - name: Validate {{ home_dir }}/.ssh/id_rsa is present 
    assert: 
      that: "command_result.stat.exists == true" 
      msg: "The private key must exist for the agent node to configure other nodes"
  tags: agent
      
# Disable automatic updates in CoreOS
- hosts: all
  gather_facts: false
  tasks:
    - include: tasks/disable-automatic-updates.yml
  become: true
  become_method: sudo
  tags: init


# Prepare the agent as a cache to repeteadly boostrap the cluster
- hosts: agent
  gather_facts: false
  roles: 
    - pre-any
    - agent
  post_tasks:
    - include: tasks/transfer-certFiles.yml
    - include: tasks/prep-admin-kubeconfig.yml
    - include: tasks/prep-admin-remote-kubeconfig.yml
    - include: tasks/prep-kubeClient.yml
  tags: agent


