---

- hosts: [ etcd, kube-masters, kube-addon-workers ]
  gather_facts: false
  pre_tasks:
    - include: tasks/transfer-prepFiles.yml
  roles:
    - pre-any
  post_tasks:
    - include: tasks/transfer-certFiles.yml
  strategy: free
  tags: always

- hosts: etcd
  gather_facts: false
  roles: 
    - etcd 
  strategy: free
  tags: etcd


- hosts: kube-nodes
  gather_facts: false
  pre_tasks:
    - include: tasks/transfer-imageFiles.yml
  roles:
    - pre-kube
    - flannel
  post_tasks:
    - include: tasks/prep-admin-kubeconfig.yml
    - include: tasks/prep-kubeClient.yml
  strategy: free
  tags: kube-nodes

- hosts: kube-masters
  gather_facts: false
  roles:
    - kube-master
  strategy: free
  tags: kube-masters

- hosts: kube-masters
  gather_facts: false
  roles:
    - kube-master-extras
  tags: kube-master-extras

- hosts: kube-addon-workers
  gather_facts: false
  roles:
    - kube-worker
  strategy: free
  tags: kube-addon-workers


- hosts: [ etcd, kube-masters, kube-addon-workers ]
  gather_facts: false
  tasks:
    - include: tasks/cleanup-deployment-artifacts.yml
  strategy: free
  tags: always



