---

- hosts: all
  gather_facts: false
  tasks:
    - include: tasks/disable-automatic-updates.yml
  become: true
  become_method: sudo
  tags: init

- hosts: agent
  gather_facts: false
  roles: 
    - pre-any
    - agent
  post_tasks:
    - include: tasks/transfer-certFiles.yml
    - include: tasks/prep-admin-kubeconfig.yml
    - include: tasks/prep-admin-remote-kubeconfig.yml
    - include: tasks/prep-kubeClient.yml
  tags: agent


