---

- hosts: agent
  gather_facts: false
  vars:
    ssh_dir: ../.ssh
    private_key_file: "{{ ssh_dir }}/id_rsa"
  tasks:
    - name: Stat file {{ private_key_file }}
      stat: path={{ private_key_file }}
      register: command_result

    - name: Ensure {{ ssh_dir }} directory exists
      file: path={{ ssh_dir }} state=directory mode=0644 recurse=true
      become: true
      become_method: sudo

    - name: Create {{ private_key_file }} key pair if not present 
      shell: |
        ls .ssh | grep -q id_rsa || ssh-keygen -b 2048 -t rsa -f .ssh/id_rsa -q -N ''
      args:
        chdir: "{{ ssh_dir }}"
      when: command_result.stat.exists == false 
      delegate_to: 127.0.0.1

    - name: Copy ../.ssh/id_rsa to the agent node
      copy: src=../.ssh/id_rsa dest=/home/core/.ssh/id_rsa owner=core group=core mode=0600

  tags: agent


